### ISSUE TITLE
Assignment-7

### ISSUE THREAD

**Issue by emilykschwabe** [emilykschwabe/Assignment7#1]
Hi Mark, 

I explored the R package kinship 2 for this assignment. It's a pretty cool package I've been using for an independent project. I added the formal vignette (not my own) for this package. I wasn't completely sure what you meant in the instructions, but I hope that addition was right. Thanks!

**Comment by mdscheuerell** [comment]
This is really well done, Emily! And it's super cool that you made your own website for the package as well!
